name: "Build Test"
on:
  push

jobs:
  build_test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: "install"
        run: npm install
      - name: "build"
        run: npm run build
