name: 'Build'
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: 'Install node modules'
        run: yarn install
      - name: 'Build for production'
        run: yarn build
