name: "Build Test"
on:
  push
strategy:
  matrix:
    node: [10, 12, 14, 16]
jobs:
  releasee:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: "install"
        run: yarn install
