name: "Unit Test"
on:
  push

jobs:
  unit_test:
    name: unit_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: "Install node modules"
        run: yarn install
      - name: "Run Unit Test"
        run: yarn test:unit
